import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
